github-ci: add build check on M1 with ARM64
Added new Github Action workflow to check the M1 with Tarantool build
as file: '.github/workflows/osx_arm64_11_2.yml'.

Added in Github Action workflow prefix to run all commands from
makefile 'arch -arm64', otherwise found that Github Action uses
'arch -x86_64' prefix by default.

Found that cmake fails running, like:

  CMake Warning (dev):
    Policy CMP0068 is not set: RPATH settings on macOS do not affect
    install_name.  Run "cmake --help-policy CMP0068" for policy details.  Use
    the cmake_policy command to set the policy and suppress this warning.

    For compatibility with older versions of CMake, the install_name fields for
    the following targets are still affected by RPATH settings:

     cfunc1
     cfunc2
     cfunc3
     cfunc4
     check_merge_source
     func_restore1
     func_restore2
     func_restore3
     func_restore4
     function1
     gh-5938-wrong-string-length
     lib1
     lib11
     lib2
     lib21
     libflush
     libluajit_shared
     libsandwich
     libyield
     loaderslib
     module_api
     on_shutdownlib
     reload1
     reload2
     testgetmetrics
     tuple_bench

  This warning is for project developers.  Use -Wno-dev to suppress it.

To avoid of it added '-Wno-dev' flag to cmake command.

In .travis.mk makefile created new target to test only Tarantool build
on M1: 'test_osx_arm64_github_actions'.

Found that on M1 hosts running python3 installation python3.9 is
installing by default. But we need to install gevent as test
required package, which fails to be installed with python3.9.5
and successfully installs with python3.8.2 (python@3.8):

  Using cached gevent-21.1.2.tar.gz (5.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /opt/homebrew/opt/python@3.9/bin/python3.9 /opt/homebrew/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/b0/1vlv5rvn77x2rn6zbl2p4tqr0000gp/T/tmpyy59ae2p
         cwd: /private/var/folders/b0/1vlv5rvn77x2rn6zbl2p4tqr0000gp/T/pip-install-msbf7_vz/gevent_c2956687bb0d4de9bfb5f0660da759ee
    Complete output (42 lines):
      ...
      File "/private/var/folders/b0/1vlv5rvn77x2rn6zbl2p4tqr0000gp/T/pip-build-env-1lesbbxi/overlay/lib/python3.9/site-packages/cffi/api.py", line 48, in __init__
        import _cffi_backend as backend
    ImportError: dlopen(/private/var/folders/b0/1vlv5rvn77x2rn6zbl2p4tqr0000gp/T/pip-build-env-1lesbbxi/overlay/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so, 2): no suitable image found.  Did find:
    	/private/var/folders/b0/1vlv5rvn77x2rn6zbl2p4tqr0000gp/T/pip-build-env-1lesbbxi/overlay/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so: mach-o, but wrong architecture
    	/private/var/folders/b0/1vlv5rvn77x2rn6zbl2p4tqr0000gp/T/pip-build-env-1lesbbxi/overlay/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so: mach-o, but wrong architecture

To avoid of it changed python3 to python@3.8 in brew installation.

Closes tarantool/tarantool-qa#120